### ISSUE TITLE
capitalization error on src/app/providers/dispatch.ts

### ISSUE THREAD

**Issue by netforce** [Resgrid/Dispatch#2]
Running 'npm run build'

`ERROR in src/app/providers/dispatch.ts:11:40 - error TS2307: Cannot find module '../core/models/GetSetUnitStatusResult' or its corresponding type declarations.`
`11 import { GetSetUnitStatusResult } from '../core/models/GetSetUnitStatusResult';`

Line 11 in dispatch.ts points to ` '../core/models/GetSetUnitStatusResult';` which should be  `../core/models/getSetUnitStatusResult` without Capital 'G"

**Comment by ucswift** [comment]
hey @netforce thanks for reporting this. This is the latest v3 api code we cherry-picked from our internal git repo. We have a v4 api version with that issue fixed in it internally and as soon as we get the v4 api changes pushed out to Core we'll get this repo updated.

**Comment by ucswift** [comment]
Dispatch has been migrated to the v4 api and it's install is docker container based now. If you have any further trouble please open a new issue.
